export const styles = {
    flexCenter: 'flex justify-center items-center',
    flexStart: 'flex justify-center items-start',
    flexStart2: 'flex justify-start items-center',
    flexEvenly: 'justify-evenly flex items-center',
    flexBtw: 'justify-between flex items-center',
    flexBtw2: 'justify-between flex items-end',
    flexBtw3: 'justify-between flex items-center md:justify-evenly',
    flexEnd1: 'flex justify-start items-end',
    flexMobile1: 'md:flex-row flex-col',
    flexMobile2: 'flex md:flex-row flex-col',
    flexY: 'flex flex-col',
    widthMobile: 'md:w-[50%] w-[100%]',
    position: 'md:absolute relative',
    container1: (darkMode) => `${darkMode ? 'bg-darkMain text-gray-200' : 'bg-[#fff]'} overflow-hidden`,
    container2: (darkMode) => `${darkMode ? 'bg-darkMain' : 'bg-[#fff]'}`,
    container3: (darkMode) => `${darkMode ? 'bg-darkMain text-gray-200' : 'text-slate-900'}`,
    gradient: 'bg-gradient-to-r from-[#9060DA] to-[#28A2CF] bg-clip-text text-transparent',
    title: 'futura font-black text-5xl mb-3',
    title2: 'futura font-black md:text-4xl text-3xl tracking-wider mb-4',
    darkText1: (darkMode) => `${darkMode ? 'text-gray-200' : 'text-gray-800'}`,
    darkText2: (darkMode) => `${darkMode ? 'text-gray-200' : 'text-gray-600'}`,
    headingCont: 'flex flex-col max-w-[300px] mb-[5rem] items-center justify-center',
    headingH1: 'futura font-bold tracking-widest text-4xl inline-block text-gray-200 pb-2',
    headingH1Two: (darkMode) =>  `${darkMode ? ' text-gray-200' : 'text-slate-800' } futura font-bold tracking-widest text-4xl inline-block  pb-2`,
    line: 'h-0.5 w-[170px] -translate-x-4  bg-indigo-600 mt-2',
    gitBtn: 'flex items-center gt md:text-xl text-md mr-3 shadow-md transition-all bg-indigo-500 px-3 shadow-indigo-400 py-2 rounded-md hover:bg-indigo-400 text-white',
    dwdBtn: 'flex gt items-center md:text-xl text-md border-2 px-3 py-2 hover:text-white transition-all rounded-md shadow-md border-indigo-500 hover:bg-blue-400 hover:border-blue-400',
    contactBtn: 'text-white gt text-xl mr-3 shadow-md mt-6 transition-all bg-indigo-500 px-3 shadow-indigo-400 py-2 rounded-md hover:bg-indigo-400',
    writer: 'text-6xl text-gray-200 gt font-black md:text-5xl bg-gradient-to-r from-[#9060DA] to-[#28A2CF] bg-clip-text text-transparent'
}